2020-04-28 14:26:05,965 INFO: Microblog startup [in /home/obu/microblog/app/__init__.py:44]
2020-04-28 14:26:24,375 ERROR: Exception on /editprofile [GET] [in /home/obu/microblog/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/obu/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/obu/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/obu/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/obu/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/obu/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/obu/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/obu/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/obu/microblog/app/routes.py", line 95, in edit_profile
    return render_template('edit_profile.html', title ="Edit Profile", form = form)
  File "/home/obu/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/obu/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/obu/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/obu/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/obu/microblog/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/obu/microblog/app/templates/edit_profile.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/obu/microblog/app/templates/base.html", line 32, in top-level template code
    {% block content%}{% endblock %}
  File "/home/obu/microblog/app/templates/edit_profile.html", line 23, in block "content"
    <p>{{ form.submit() }} </p>
jinja2.exceptions.UndefinedError: 'app.forms.EditProfileForm object' has no attribute 'submit'
2020-04-28 14:27:52,681 INFO: Microblog startup [in /home/obu/microblog/app/__init__.py:44]
2020-04-28 14:32:59,032 INFO: Microblog startup [in /home/obu/microblog/app/__init__.py:44]
2020-05-01 12:41:44,236 INFO: Microblog startup [in /home/obu/microblog/app/__init__.py:44]
2020-05-01 12:41:52,799 INFO: Microblog startup [in /home/obu/microblog/app/__init__.py:44]
2020-05-01 21:20:20,701 INFO: Microblog startup [in /home/obu/microblog/app/__init__.py:44]
2020-05-01 21:27:17,963 INFO: Microblog startup [in /home/obu/microblog/app/__init__.py:44]
2020-05-01 21:28:20,975 INFO: Microblog startup [in /home/obu/microblog/app/__init__.py:44]
2020-05-01 21:29:54,231 INFO: Microblog startup [in /home/obu/microblog/app/__init__.py:44]
2020-05-01 21:30:48,982 INFO: Microblog startup [in /home/obu/microblog/app/__init__.py:44]
2020-05-01 21:31:59,649 INFO: Microblog startup [in /home/obu/microblog/app/__init__.py:44]
2020-05-01 21:32:31,241 INFO: Microblog startup [in /home/obu/microblog/app/__init__.py:44]
2020-05-01 21:33:17,283 INFO: Microblog startup [in /home/obu/microblog/app/__init__.py:44]
2020-05-01 21:51:02,040 INFO: Microblog startup [in /home/obu/microblog/app/__init__.py:44]
2020-05-01 21:51:11,882 ERROR: Exception on /user/obulesu [GET] [in /home/obu/microblog/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/obu/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/obu/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/obu/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/obu/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/obu/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/obu/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/obu/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/obu/microblog/app/routes.py", line 74, in user
    return render_template('user.html', user=user, posts = posts)
  File "/home/obu/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/obu/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/obu/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/obu/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/obu/microblog/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/obu/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/obu/microblog/app/templates/base.html", line 32, in top-level template code
    {% block content%}{% endblock %}
  File "/home/obu/microblog/app/templates/user.html", line 13, in block "content"
    <p>{{ users.followers.count() }} followers, {{user.followed.count() }} following.</p>
  File "/home/obu/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'users' is undefined
2020-05-01 21:52:22,289 INFO: Microblog startup [in /home/obu/microblog/app/__init__.py:44]
2020-05-02 14:34:10,962 INFO: Microblog startup [in /home/obu/microblog/app/__init__.py:44]
2020-05-02 14:36:51,110 INFO: Microblog startup [in /home/obu/microblog/app/__init__.py:44]
2020-05-02 14:38:04,442 INFO: Microblog startup [in /home/obu/microblog/app/__init__.py:44]
2020-05-02 15:24:25,507 INFO: Microblog startup [in /home/obu/microblog/app/__init__.py:44]
2020-05-02 15:33:51,792 INFO: Microblog startup [in /home/obu/microblog/app/__init__.py:44]
2020-05-02 15:34:02,191 ERROR: Exception on /explore [GET] [in /home/obu/microblog/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/obu/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/obu/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/obu/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/obu/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/obu/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/obu/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/obu/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/obu/microblog/app/routes.py", line 132, in explore
    next_url = url_for('index', page= posts.next_num) if posts.has_next else None
UnboundLocalError: local variable 'posts' referenced before assignment
2020-05-02 15:36:11,609 INFO: Microblog startup [in /home/obu/microblog/app/__init__.py:44]
2020-05-02 15:41:18,586 INFO: Microblog startup [in /home/obu/microblog/app/__init__.py:44]
2020-05-02 15:45:14,637 INFO: Microblog startup [in /home/obu/microblog/app/__init__.py:44]
2020-05-02 15:49:35,326 INFO: Microblog startup [in /home/obu/microblog/app/__init__.py:44]
2020-05-02 15:52:05,193 INFO: Microblog startup [in /home/obu/microblog/app/__init__.py:44]
2020-05-02 15:54:26,542 INFO: Microblog startup [in /home/obu/microblog/app/__init__.py:44]
2020-05-02 15:56:15,634 INFO: Microblog startup [in /home/obu/microblog/app/__init__.py:44]
2020-05-02 16:00:00,184 INFO: Microblog startup [in /home/obu/microblog/app/__init__.py:44]
2020-05-02 16:01:18,284 INFO: Microblog startup [in /home/obu/microblog/app/__init__.py:44]
2020-05-02 16:05:51,963 INFO: Microblog startup [in /home/obu/microblog/app/__init__.py:44]
2020-05-02 17:25:06,572 INFO: Microblog startup [in /home/obu/microblog/app/__init__.py:46]
2020-05-02 17:30:50,734 INFO: Microblog startup [in /home/obu/microblog/app/__init__.py:46]
2020-05-02 18:32:14,556 INFO: Microblog startup [in /home/obu/microblog/app/__init__.py:46]
